// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNyaLzeq5_g2m075obOD5MT0nzkaWA5Yc',
    appId: '1:933744392266:android:00ba16663cbeeb49870eb3',
    messagingSenderId: '933744392266',
    projectId: 'entrate-uscite-47b9e',
    storageBucket: 'entrate-uscite-47b9e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJkKvaQMdsEBovVF8uNJw_xQRw3ka_peE',
    appId: '1:933744392266:ios:7d4c823f8f48f944870eb3',
    messagingSenderId: '933744392266',
    projectId: 'entrate-uscite-47b9e',
    storageBucket: 'entrate-uscite-47b9e.firebasestorage.app',
    iosBundleId: 'com.example.entrateUscite',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZEa6D2swzVNnykDfkCUbNRMRJZ1dr5k',
    appId: '1:933744392266:web:df674b8f08da563b870eb3',
    messagingSenderId: '933744392266',
    projectId: 'entrate-uscite-47b9e',
    authDomain: 'entrate-uscite-47b9e.firebaseapp.com',
    storageBucket: 'entrate-uscite-47b9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJkKvaQMdsEBovVF8uNJw_xQRw3ka_peE',
    appId: '1:933744392266:ios:7d4c823f8f48f944870eb3',
    messagingSenderId: '933744392266',
    projectId: 'entrate-uscite-47b9e',
    storageBucket: 'entrate-uscite-47b9e.firebasestorage.app',
    iosBundleId: 'com.example.entrateUscite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdZEa6D2swzVNnykDfkCUbNRMRJZ1dr5k',
    appId: '1:933744392266:web:2cbbd4b9907f8d69870eb3',
    messagingSenderId: '933744392266',
    projectId: 'entrate-uscite-47b9e',
    authDomain: 'entrate-uscite-47b9e.firebaseapp.com',
    storageBucket: 'entrate-uscite-47b9e.firebasestorage.app',
  );

}